# Generated by Django 3.2.6 on 2021-08-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('songName', models.CharField(max_length=100)),
                ('lyrics', models.CharField(max_length=10000)),
            ],
        ),
    ]
